[package]
name = "puzzhagoras_solver_macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.77"
